### ISSUE TITLE
Owner of Riglos made a song about Fairfax named Refuse to fairfax

### ISSUE THREAD

**Issue by ghost** [kreativekorp/open-relay#35]
Refuse to fairfax I hate you It is polite Poland - Rebecca war I hate you but I Downloaded it But only the Italic and the HD Constructium too, because Piotr Hates Rebecca, please Download fairfax Because Rebecca will be happy I forgot You shall yes say yes this day I shall it but download it Delete Rebecca - stop f''cking moving Move on - mode - more Mode more mode more mode more Riglos Is Not Fairfax but mode more Mode more ashuk mode more assoc it Mode More - DOS and TRES KurwaWarku Awruk Awruk is Mode More Dos And Traa Trap traps it and rap raps it, so Red Green Blue is Windows 8.1, my god! Vista, 7, 8.1 or 10? Fairfax, download It in a second!!! But Delete If You Want... Refuse to faaaaaaaaaaaaaaaiiiiiirrrffaaaaxxxx Faaaiirrrffaaaxxx reeeeefffuuussseeeeeesss Meeeeeeeeee moooodddeee moooorrrreeee Moooolddddeee moooorrrreeee aaaaand Faiiirrfaxxxxxaxaxxxaaaaaa is refusing It it kt it it it it kt it it it it Faaaaiiirrffaaxxx lloooovveeesss F A I R F A X! Refuse to Fafafafafafafafafaiaiaiaiaiaiaiaiarararararararararararafafafafafafafafafafafafaaaaaaaaaaaaaaaaaaaaaaaaaaairfax!! To the fafafafaiaiaiararafax! SYSTEM! F A I R F A X!

**Comment by Hidisksjdjdjgjgkxjskdkgigiduyjksdltrkdz** [comment]
Make this play on your Fairfax page

**Comment by den32ds** [comment]
@RebeccaRGB wtf is going on? who is this guy?

**Comment by Idjajmakauhdhshhauaj** [comment]
> @RebeccaRGB wtf is going on? who is this guy?

RebeccaRGB makes Kreative stuff which is very uncreative. She also refuses to self-promote or be self-promoted, making users who come across have no idea what competes with Kreative. She is also spoiled, as evidenced by sarcastic comments on the tiling system in legacy fonts, and taking the ability to go beyond boundaries in TrueType for granted way too much, even though it detaches from the legacy font style (which [Custom Font ttf](https://typedesign.netlify.com/customfont.html) and [Riglos Mono](https://typedesign.netlify.com/riglos.html) preserve. In reality, vertical out of bounds should not be done in fonts because it gets clipped in GDI, the main engine of Microsoft Windows, and it prevents Fairfax to be used in theoretical legacy environments because, in some stage during porting the font it will be clipped because legacy glyph grids don't have overlapping glyphs. This makes it unclear what Legacy Computing characters are used for in the font, let alone inverse characters where suddenly the boundaries apply. It also prevents the peace of mind that Fairfax would be a legacy font, because exceeding boundaries contradicts that. This is awful.

**Comment by RebeccaRGB** [comment]
@den32ds This guy is a novice type designer with no idea what he's doing. He keeps spamming my GitHub repositories with advertisements for his own fonts (only sometimes with a thin veneer of a legitimate issue), tried to blackmail me into advertising on his crappy website, and has been harassing me since March 12. I've blocked him many times but he keeps creating new accounts.

**Comment by RebeccaRGB** [comment]
@den32ds This guy is a novice type designer with no idea what he's doing. He keeps spamming my GitHub repositories with advertisements for his own fonts (only sometimes with a thin veneer of a legitimate issue), tried to blackmail me into advertising on his crappy website, and has been harassing me since March 12. I've blocked him many times but he keeps creating new accounts.
