### ISSUE TITLE
horizontally alignment for t, f seems to be at too right

### ISSUE THREAD

**Issue by eypsume** [kreativekorp/open-relay#63]
horizontally alignment for t, f seems to be at too right,
Here's simple compared other fonts,
![image](https://user-images.githubusercontent.com/38209036/103762273-6152e280-505b-11eb-8e17-d639969eae38.png)

**Comment by JapanYoshi** [comment]
FYI, it's the same with the pixelated Fairfax:
![image](https://user-images.githubusercontent.com/8707990/169719342-ac5442cf-8f49-43d4-9269-1583015cd230.png)
![image](https://user-images.githubusercontent.com/8707990/169719343-5a82acce-dcb9-4830-908b-9ddc95c0a9a7.png)
Redesigning the characters to have the vertical on the 2nd column instead of the 3rd COULD make for a better flow, but I personally don't see the necessity for that.

For reference, here's FixedSys:
![image](https://user-images.githubusercontent.com/8707990/169719380-d7527163-272c-431e-a5ed-fe2b65aa0e47.png)
and the font used for CGA graphics cards:
![image](https://user-images.githubusercontent.com/8707990/169719396-327c53e3-fe3c-4b6e-9564-a7bbdbfcfd79.png)

I don't happen to have any samples of smaller pixel-size fonts (like Monaco), so I don't know how they approach it.
