### ISSUE TITLE
Various questions about Fairfax HD

### ISSUE THREAD

**Issue by oshaboy** [kreativekorp/open-relay#72]
Where did the Commander X16 Symbols block (F5C0-F5FE) come from? The only one I've seen is F5FF which is part of the Commander X16 font ROM. 

What is a Dogcow (F607) and why does Betty Boop (FB009) get a block?

Are the Pico-8 symbols at FF800-FF80F stable or are they subject to change? Was making them narrower than the actual Pico-8 the intention?

**Comment by RebeccaRGB** [comment]
The other characters in the CX16 block are from someone's early proposal for the character set that was not adopted.

This is a Dogcow: https://en.wikipedia.org/wiki/Dogcow

Betty Boop comes from this easter egg: https://www.unicode.org/charts/PDF/UBOOP.pdf

The Pico-8 symbols are stable. Their width is intentional, because Fairfax (HD) is a monospaced (well, duospaced) font.
